### PR TITLE
Add new task

### PR DESCRIPTION
**Pull request by KaranGohil**

### CODE REVIEW

**Comment by KaranGohil** [comment]
I have added a new task. Please review it

**Comment by KaranGohil** [comment]
There is also conflict. Should I resolve it?

**Review by jayantpuri — COMMENTED** [review]
looks good to me

**Comment by shiro102** [comment]
You should resolve conflict on your own.

**Comment by KaranGohil** [comment]
I resolved it!

**Review by shiro102 — COMMENTED** [review]
Checked

**Review by shiro102 — APPROVED** [review]
Checked

**Comment by sirusw** [comment]
That looks decent!

**Comment by sirusw** [comment]
All reviewers have done the review.

**Pull request closed without merging**
